# Generated by Django 4.2.1 on 2024-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCheApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
