# Generated by Django 4.2.1 on 2024-03-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCheApp', '0002_repository_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
